---
title: "pairwise FST population-wide"
author: "Sarah Mueller"
date: "2023-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2, lib = "/dss/dsshome1/lxc0B/ra52qed/R/x86_64-pc-linux-gnu-library/4.2")
library(plyr)
library(dplyr)
library(broom)
library(readxl)
library(tidyverse)

```

##Vcftools fst

I wat to plot all pop-wide fst statistics across rustica subspecies


```{r message=FALSE, warning=FALSE}
fst.results <- read.table("/dss/dsslegfs01/pr53da/pr53da-dss-0034/projects/2021_SwallowWGS_168/1_Population_Structure/4_pixy/2_FST/1_fst_avg_5kb_gw.txt", header=T)

#follwoign creates a duplicate where pop1=pop2 and vice versa for heatmap plotting
# Create a copy of the original dataframe and switch the values of pop1 and pop2 columns
fst.copy <- fst.results %>% 
  transmute(pop1 = fst.results$pop2, pop2 = fst.results$pop1, FST = fst.results$FST, avg_fst = fst.results$avg_fst)
# Combine the two dataframes using bind_rows
fst.results <- bind_rows(fst.results, fst.copy)

#add sample pops
fst.results <- fst.results %>%
  mutate(pop1 = case_when(
    grepl("rustica.r", pop1) ~ "RUr",
    grepl("rustica.eu", pop1) ~ "RUe",
    grepl("rustica.eu", pop1) ~ "RUe",
    grepl("rustica.eu", pop1) ~ "RUe",
    grepl("gutturalis", pop1) ~ "GU",
    grepl("erythrogaster", pop1) ~ "ER",
    grepl("savignii", pop1) ~ "SA",
    grepl("transitiva", pop1) ~ "TR",
    grepl("tytleri", pop1) ~ "TY"))

#add sample pops
fst.results <- fst.results %>%
  mutate(pop2 = case_when(
    grepl("rustica.r", pop2) ~ "RUr",
    grepl("rustica.eu", pop2) ~ "RUe",
    grepl("rustica.eu", pop2) ~ "RUe",
    grepl("rustica.eu", pop2) ~ "RUe",
    grepl("gutturalis", pop2) ~ "GU",
    grepl("erythrogaster", pop2) ~ "ER",
    grepl("savignii", pop2) ~ "SA",
    grepl("transitiva", pop2) ~ "TR",
    grepl("tytleri", pop2) ~ "TY"))

```

## make heatmap

make heatmap of results

```{r message=FALSE, warning=FALSE}

# Define population order
pop_order <- c("SA", "TR", "RUe", "RUr", "GU", "TY", "ER")

# Apply factor levels
fst.results <- fst.results %>%
  mutate(
    pop1 = factor(pop1, levels = pop_order),
    pop2 = factor(pop2, levels = pop_order)
  )

# Plot heatmap
heatmap_2 <- ggplot(fst.results, aes(x = pop1, y = pop2, fill = avg_fst)) + 
  geom_tile(
    data = subset(fst.results, as.integer(pop1) < as.integer(pop2)), 
    aes(fill = avg_fst),
    color = "black", size = 0.2
  ) +
  geom_text(
    data = subset(fst.results, as.integer(pop1) < as.integer(pop2)), 
    aes(label = sprintf("%0.3f", round(avg_fst, digits = 3)))
  ) +
  coord_fixed() +
  scale_fill_gradient2(
    low = "#8EC3E6", mid= "#e6f3f8", high = "red",
    midpoint = 0.025,
    limits = c(0.0, 0.055),
    breaks = c(0.01, 0.03, 0.05),
    labels = scales::number_format(accuracy = 0.01)
  ) +
  theme(
    axis.text.x = element_text(size = 10), 
    axis.text.y = element_text(size = 10), 
    axis.title = element_blank(), 
    legend.title = element_text(size = 12),
    legend.position = c(0.95, 0.1),   # bottom-right corner inside
    legend.justification = c("right", "bottom"),
    legend.background = element_rect(fill = "white", color = "white"),
    legend.key.size = unit(0.6, "cm"),
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank()
  ) +
  labs(fill = expression(F[ST]))

heatmap_2
```
Save image

```{r}
ggsave("/dss/dsslegfs01/pr53da/pr53da-dss-0034/projects/2021_SwallowWGS_168/1_Population_Structure/4_pixy/2_FST/2_Figure1c_FST_heatmap.png", plot = heatmap_2, width = 5, height = 4, units = "in", dpi = 500)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
